// <auto-generated />
using System;
using BookingService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingService.Persistence.Migrations
{
    [DbContext(typeof(BookingServiceDbContext))]
    partial class BookingServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingService.Persistence.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingPlaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("end_time");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("start_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("BookingService.Persistence.Entities.BookingPlaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("address");

                    b.HasKey("Id");

                    b.ToTable("booking_places", (string)null);
                });

            modelBuilder.Entity("BookingService.Persistence.Entities.HallEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_place_id");

                    b.Property<string>("ComputerSpec")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("computer_spec");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_per_hour");

                    b.Property<string>("floorUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingPlaceId");

                    b.ToTable("halls", (string)null);
                });

            modelBuilder.Entity("BookingService.Persistence.Entities.SeatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid")
                        .HasColumnName("hall_id");

                    b.Property<int>("NumberInHall")
                        .HasColumnType("integer")
                        .HasColumnName("number_in_hall");

                    b.Property<string>("PositionJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "NumberInHall")
                        .IsUnique()
                        .HasDatabaseName("idx_seats_hall_number_unique");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("BookingService.Persistence.Entities.BookingEntity", b =>
                {
                    b.HasOne("BookingService.Persistence.Entities.SeatEntity", "Seat")
                        .WithMany("Bookings")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("BookingService.Persistence.Entities.HallEntity", b =>
                {
                    b.HasOne("BookingService.Persistence.Entities.BookingPlaceEntity", "BookingPlace")
                        .WithMany("Halls")
                        .HasForeignKey("BookingPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingPlace");
                });

            modelBuilder.Entity("BookingService.Persistence.Entities.SeatEntity", b =>
                {
                    b.HasOne("BookingService.Persistence.Entities.HallEntity", "Hall")
                        .WithMany("Seats")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("BookingService.Persistence.Entities.BookingPlaceEntity", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("BookingService.Persistence.Entities.HallEntity", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("BookingService.Persistence.Entities.SeatEntity", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
